In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline

In [2]:
df = pd.read_csv('heart_disease_cleaned.csv')
df.head()

Unnamed: 0  Age  Sex  Chest_Pain  Resting_Blood_Pressure  Colestrol  \
0           0   63    1           1                     145        233   
1           1   67    1           4                     160        286   
2           2   67    1           4                     120        229   
3           3   37    1           3                     130        250   
4           4   41    0           2                     130        204   

   Fasting_Blood_Sugar  Rest_ECG  MAX_Heart_Rate  Exercised_Induced_Angina  \
0                    1         2             150                         0   
1                    0         2             108                         1   
2                    0         2             129                         1   
3                    0         0             187                         0   
4                    0         2             172                         0   

   ST_Depression  Slope  Major_Vessels  Thalessemia  Target  
0            2.3      3              0            6       0  
1            1.5      2              3            3       2  
2            2.6      2              2            7       1  
3            3.5      3              0            3       0  
4            1.4      1              0            3       0

In [3]:
df.drop('Unnamed: 0',axis=1, inplace = True)
df.head()

Age  Sex  Chest_Pain  Resting_Blood_Pressure  Colestrol  \
0   63    1           1                     145        233   
1   67    1           4                     160        286   
2   67    1           4                     120        229   
3   37    1           3                     130        250   
4   41    0           2                     130        204   

   Fasting_Blood_Sugar  Rest_ECG  MAX_Heart_Rate  Exercised_Induced_Angina  \
0                    1         2             150                         0   
1                    0         2             108                         1   
2                    0         2             129                         1   
3                    0         0             187                         0   
4                    0         2             172                         0   

   ST_Depression  Slope  Major_Vessels  Thalessemia  Target  
0            2.3      3              0            6       0  
1            1.5      2              3            3       2  
2            2.6      2              2            7       1  
3            3.5      3              0            3       0  
4            1.4      1              0            3       0

In [5]:
from sklearn.linear_model import SGDClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report,confusion_matrix,auc,roc_auc_score,roc_curve
from sklearn.model_selection import train_test_split

In [20]:
from sklearn.metrics import multilabel_confusion_matrix

In [22]:
from sklearn.metrics import balanced_accuracy_score

In [6]:
from sklearn.naive_bayes import GaussianNB

In [7]:
X = df.drop('Target',axis=1)
y = df['Target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=40)

In [11]:
scaler = StandardScaler()
scaler.fit(df.drop('Target',axis=1))

StandardScaler()

In [12]:
scaled_features = scaler.transform(df.drop('Target',axis=1))

In [13]:
df_feat = pd.DataFrame(scaled_features,columns=df.columns[:-1])

In [14]:
df_feat.head()

Age       Sex  Chest_Pain  Resting_Blood_Pressure  Colestrol  \
0  0.942285  0.687486   -2.237510                0.747060  -0.273149   
1  1.385714  0.687486    0.871893                1.592788   0.816946   
2  1.385714  0.687486    0.871893               -0.662487  -0.355421   
3 -1.939999  0.687486   -0.164574               -0.098668   0.076504   
4 -1.496571 -1.454575   -1.201042               -0.098668  -0.869617   

   Fasting_Blood_Sugar  Rest_ECG  MAX_Heart_Rate  Exercised_Induced_Angina  \
0             2.425638  1.013652        0.019003                 -0.698167   
1            -0.412263  1.013652       -1.812373                  1.432322   
2            -0.412263  1.013652       -0.896685                  1.432322   
3            -0.412263 -1.000046        1.632359                 -0.698167   
4            -0.412263  1.013652        0.978296                 -0.698167   

   ST_Depression     Slope  Major_Vessels  Thalessemia  
0       1.069137  2.264087      -0.723832     0.660262  
1       0.382849  0.645320       2.473994    -0.890830  
2       1.326494  0.645320       1.408052     1.177293  
3       2.098568  2.264087      -0.723832    -0.890830  
4       0.297063 -0.973448      -0.723832    -0.890830

In [15]:
X = df_feat
y = df['Target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=40)

In [16]:
sgd_clf = SGDClassifier()
sgd_clf.fit(X_train,y_train)

SGDClassifier()

In [28]:
gnb = GaussianNB().fit(X_train, y_train)
gnb_predictions = gnb.predict(X_test)
  
cm = confusion_matrix(y_test, gnb_predictions)

In [30]:
pred = sgd_clf.predict(X_test)

print('Stochastic Gradient Descent:') 
print('\n')
print(multilabel_confusion_matrix(y_test, pred))
print('\n')
print(classification_report(y_test,pred))
print(balanced_accuracy_score(y_test,pred))
print('\n')
print('\n')
print('Naive Bayes:')
print('\n')
print(multilabel_confusion_matrix(y_test, gnb_predictions))
print('\n')
print(classification_report(y_test,gnb_predictions))
print(balanced_accuracy_score(y_test,gnb_predictions))

Stochastic Gradient Descent:


[[[18 22]
  [10 39]]

 [[63 11]
  [10  5]]

 [[78  1]
  [10  0]]

 [[73  2]
  [12  2]]

 [[81  7]
  [ 1  0]]]


              precision    recall  f1-score   support

           0       0.64      0.80      0.71        49
           1       0.31      0.33      0.32        15
           2       0.00      0.00      0.00        10
           3       0.50      0.14      0.22        14
           4       0.00      0.00      0.00         1

    accuracy                           0.52        89
   macro avg       0.29      0.25      0.25        89
weighted avg       0.48      0.52      0.48        89

0.25442176870748295




Naive Bayes:


[[[36  4]
  [ 6 43]]

 [[67  7]
  [12  3]]

 [[69 10]
  [ 9  1]]

 [[63 12]
  [ 9  5]]

 [[84  4]
  [ 1  0]]]


              precision    recall  f1-score   support

           0       0.91      0.88      0.90        49
           1       0.30      0.20      0.24        15
           2       0.09      0.10      0.10        10
